mode: eval
feature_extractors:
  stat:
    type: stat
    args: []
    n_features: 12
  conv:
    type: conv
    args: ['./models/conv_v1.h5']
    n_features: 64
binary_features_serialization:
  path: ./temp/
eval:
  data_path: ./data/eval/patches-wsi-224-val-z2/
  classes: [
            {name: AT, n_queries: 10},
            {name: BG, n_queries: 10},
            {name: LP, n_queries: 10},
            {name: MM, n_queries: 10},
            {name: TUM, n_queries: 10}
  ]
  feature_extractor_type: conv
  feature_extractor: ${feature_extractors.${eval.feature_extractor_type}}
  binary_features_serialization: ${binary_features_serialization}
  tile_size: 112
  save_results: False
  top_n: 10
  LSH_k_bits: 32
data_generation:
  level: 0 # Levels are numbered from 0 (the highest resolution) to level_count - 1
  image_dir: ./data/WSS2/
  output_dir: ./data/VAE_data/train/
  skip_images: ['6.svs',
                '8.svs']
  n_images: 1000
  tile_size: [224, 224]
fit_VAE:
  load_checkpoint: False
  load_path: ./models/VAE_checkpoint
  save_every_steps: 100
  save_path: ./models/VAE_checkpoint
  image_dir: ./data/VAE_data/train/
  input_size: 224
  in_channels: 3
  lattent_dims: 64
  hidden_dims: []
  batch_size: 10
  lr: 0.00001
  max_steps: 1000