sources_dir: [
  '/home/artem/data/CBIR_other_data/arcDataset/Achaemenid architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/American craftsman style/',
  '/home/artem/data/CBIR_other_data/arcDataset/American Foursquare architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Ancient Egyptian architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Art Deco architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Art Nouveau architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Baroque architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Bauhaus architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Beaux-Arts architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Byzantine architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Chicago school architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Colonial architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Deconstructivism/',
  '/home/artem/data/CBIR_other_data/arcDataset/Edwardian architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Georgian architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Gothic architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Greek Revival architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/International style/',
  '/home/artem/data/CBIR_other_data/arcDataset/Novelty architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Palladian architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Postmodern architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Queen Anne architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Romanesque architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Russian Revival architecture/',
  '/home/artem/data/CBIR_other_data/arcDataset/Tudor Revival architecture/',
]
cropped_dir: /home/artem/data/CBIR_other_data/arcDataset/cropped
out_size: 112
